/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_board_free: (a: number, b: number) => void;
export const board_clone: (a: number) => number;
export const board_default: (a: number, b: number) => number;
export const board_get_block_tblr: (a: number, b: number) => [number, number];
export const board_get_height: (a: number) => number;
export const board_get_index: (a: number, b: number, c: number) => number;
export const board_get_player: (a: number) => number;
export const board_get_space: (a: number, b: number) => [number, number];
export const board_get_tile: (a: number, b: number) => number;
export const board_get_width: (a: number) => number;
export const board_move_player: (a: number, b: number) => number;
export const board_move_tile: (a: number, b: number, c: number, d: number) => number;
export const board_set_block: (a: number, b: number, c: number) => void;
export const board_set_player: (a: number, b: number) => void;
export const board_set_space: (a: number, b: number, c: number) => void;
export const __wbg_block_free: (a: number, b: number) => void;
export const __wbg_get_block_bottom: (a: number) => number;
export const __wbg_get_block_left: (a: number) => number;
export const __wbg_get_block_right: (a: number) => number;
export const __wbg_get_block_top: (a: number) => number;
export const __wbg_get_tile_block: (a: number) => number;
export const __wbg_get_tile_space: (a: number) => number;
export const __wbg_set_block_bottom: (a: number, b: number) => void;
export const __wbg_set_block_left: (a: number, b: number) => void;
export const __wbg_set_block_right: (a: number, b: number) => void;
export const __wbg_set_block_top: (a: number, b: number) => void;
export const __wbg_set_tile_block: (a: number, b: number) => void;
export const __wbg_set_tile_space: (a: number, b: number) => void;
export const __wbg_tile_free: (a: number, b: number) => void;
export const block_from_tblr: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const block_pushed_side: (a: number, b: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
